### ISSUE TITLE
Namespace being removed despite being used for attribute

### ISSUE THREAD

**Issue by SudoCat** [ben-eb/postcss-discard-unused#31]
Hey,

I'm attempting to use a namespace so that I can target SVG xlink attributes. I have code that looks a little like this:
```css
@namespace xlink url('http://www.w3.org/1999/xlink');

svg:hover use[xlink|href*="facebook"] {
  fill: $facebook-blue;
}
```

But after being passed through uncss, it strips out the namespace, leaving this:

```css
svg:hover use[xlink|href*="facebook"] {
  fill: $facebook-blue;
}
```

For the time being, I've simply disabled the removing of namespaces, however it seems like the plugin doesn't notice namespaces used within attributes.

Cheers
